# Generated by Django 2.2 on 2023-11-30 23:21

from django.db import migrations, models
import django_light_enums.db


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0003_string_loyalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printing',
            name='rarity',
            field=django_light_enums.db.EnumField(choices=[(10, 'MYTHIC'), (20, 'RARE'), (30, 'UNCOMMON'), (40, 'COMMON'), (50, 'SPECIAL'), (60, 'BASIC_LAND')], default=10, enum_values=[10, 20, 30, 40, 50, 60]),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=63),
        ),
    ]
