# Generated by Django 2.2 on 2023-12-24 05:49

from django.db import migrations, models
import django.db.models.deletion
import magic_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0004_auto_20231130_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='scryfall_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(blank=True, to='magic_cards.CardSubtype'),
        ),
        migrations.AlterField(
            model_name='card',
            name='supertypes',
            field=models.ManyToManyField(blank=True, to='magic_cards.CardSupertype'),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AddField(
            model_name='printing',
            name='frame_effects',
            field=models.ManyToManyField(to='magic_cards.FrameEffect'),
        ),
        migrations.AddField(
            model_name='printing',
            name='promo_types',
            field=models.ManyToManyField(to='magic_cards.PromoType'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magic_cards.SetType'),
        ),
    ]
