# Generated by Django 2.2 on 2024-02-05 18:22

from django.db import migrations, models
import django.db.models.deletion
import magic_cards.models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0004_auto_20231130_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PromoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SetType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
            bases=(magic_cards.models.NameMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='card',
            name='subtypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='supertypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='printing',
            name='scryfall_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='scryfall_id',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='digital',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='foil_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='icon_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='nonfoil_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='set',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CardSubtype',
        ),
        migrations.DeleteModel(
            name='CardSupertype',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
        migrations.AddField(
            model_name='printing',
            name='frame_effects',
            field=models.ManyToManyField(to='magic_cards.FrameEffect'),
        ),
        migrations.AddField(
            model_name='printing',
            name='promo_types',
            field=models.ManyToManyField(to='magic_cards.PromoType'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='magic_cards.SetType'),
        ),
    ]
