# Generated by Django 2.2 on 2023-12-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magic_cards', '0005_auto_20231223_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='subtypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='supertypes',
        ),
        migrations.RemoveField(
            model_name='card',
            name='types',
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='CardSubtype',
        ),
        migrations.DeleteModel(
            name='CardSupertype',
        ),
        migrations.DeleteModel(
            name='CardType',
        ),
    ]
